# Generated by Django 4.2.6 on 2023-10-11 17:56

import app_models.models.user.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('user_name', models.CharField(help_text='30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, verbose_name='user_name')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('description', models.TextField(verbose_name='description')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
                ('date_banned', models.DateTimeField(blank=True, null=True, verbose_name='date banned')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('avatar', models.ImageField(default='files/default/user_avatar.jpg', upload_to='files/user_avatars/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('objects', app_models.models.user.manager.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='channel title')),
            ],
        ),
        migrations.CreateModel(
            name='Rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_ban', models.BooleanField(default=False, verbose_name='can ban')),
                ('can_kick', models.BooleanField(default=False, verbose_name='can kick')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='role title')),
                ('color', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='server title')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='status title')),
                ('color', models.CharField(verbose_name='status color')),
            ],
        ),
        migrations.CreateModel(
            name='RightsRole',
            fields=[
                ('rights_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_models.rights')),
            ],
            bases=('app_models.rights',),
        ),
        migrations.CreateModel(
            name='RightsServerUser',
            fields=[
                ('rights_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_models.rights')),
            ],
            bases=('app_models.rights',),
        ),
        migrations.CreateModel(
            name='TextChannel',
            fields=[
                ('channel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_models.channel')),
            ],
            bases=('app_models.channel',),
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_local', models.CharField(max_length=30, null=True, verbose_name='username local')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
                ('data_banned', models.DateTimeField(null=True, verbose_name='date banned')),
                ('is_muted', models.BooleanField(default=False, verbose_name='is muted')),
                ('mute_time', models.TimeField(null=True, verbose_name='mute time')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_models.role')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_models.server')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rights', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_models.rightsserveruser')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models.server'),
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_models.channel')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_models.role')),
                ('serveruser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_models.serveruser')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models.server'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_models.status'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='role',
            name='role_rights',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_models.rightsrole'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='text in message')),
                ('file', models.FileField(null=True, upload_to='files/user_files', verbose_name='file that will send')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='message time')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('text_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_models.textchannel')),
            ],
        ),
    ]
