# Generated by Django 4.2.6 on 2023-10-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_models.status'),
        ),
    ]
