# Generated by Django 4.2.6 on 2023-10-08 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0002_alter_user_phone_alter_user_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='phone'),
        ),
    ]
