# Generated by Django 4.2.6 on 2023-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_banned',
            field=models.DateTimeField(null=True, verbose_name='date banned'),
        ),
    ]
