from .view_server_user import ServerUserListView, ServerUserDetailView
from .view_role import RoleDetailView, RoleListView
from .view_server import ServerListView, ServerDetailView
from .view_channel import ChannelListView, ChannelDetailView
from .view_user import UserListView, UserDetailView
from .view_channel_text import ChannelTextListView, ChannelTextDetailView
from .view_channel_voice import ChannelVoiceListView, ChannelVoiceDetailView
from .view_message_reply import MessageReplyListView, MessageReplyDetailView
from .view_message import MessageListView, MessageDetailView
from .view_privilege import PrivilegeListView, PrivilegeDetailView
from .view_rights import RightsDetailView, RightsListView
from .view_rights_role import RightsRoleDetailView, RightsRoleListView
from .view_rights_server_user import RightsServerUserDetailView, RightsServerUserListView
from .view_status import StatusListView, StatusDetailView
